# Generated by Django 4.1.2 on 2023-04-18 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0009_imageset_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(max_length=500, null=True)),
                ("starting_bid", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "lifespan",
                    models.IntegerField(
                        default=10,
                        help_text="days until listing expires, to a maximum of 30.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("H", "Hats"),
                            ("AB", "Artifact (benevolent)"),
                            ("AM", "Artifact (malevolent)"),
                            ("TY", "Things That Are Yellow"),
                            ("MT", "Mineral or Tuxedo"),
                            ("CO", "Concepts, Decisions"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "imageset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="listing",
                        to="images.imageset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
