# Generated by Django 4.1.2 on 2023-04-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_alter_listing_imageset"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="posted",
            field=models.BooleanField(
                default=False,
                help_text="False = listing has not been posted; a draft. True = Listing has been posted.",
            ),
        ),
    ]
