# Generated by Django 4.1.2 on 2023-04-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0011_alter_imageset_max_size"),
        ("listings", "0008_listing_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="imageset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listing",
                to="images.imageset",
            ),
        ),
    ]
