# Generated by Django 4.1.2 on 2023-01-30 20:44

from django.db import migrations, models
import django_backblaze_b2.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_field",
                    models.ImageField(
                        storage=django_backblaze_b2.storage.BackblazeB2Storage,
                        upload_to="images",
                    ),
                ),
            ],
        ),
    ]
