# Generated by Django 4.1.2 on 2023-01-30 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_backblaze_b2.storages


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="uploaded_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="image",
            name="image_field",
            field=models.ImageField(
                storage=django_backblaze_b2.storages.PublicStorage,
                upload_to="images/user_uploads",
            ),
        ),
    ]
