# Generated by Django 4.1.2 on 2023-03-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_image_image_field_alter_image_uploaded_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-pk"]},
        ),
        migrations.AddField(
            model_name="image",
            name="alt",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_field",
            field=models.ImageField(upload_to="user_uploads"),
        ),
    ]
