# Generated by Django 4.1.2 on 2023-03-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_alter_image_options_image_alt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
