# Generated by Django 4.1.2 on 2023-03-18 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_image_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["order"]},
        ),
    ]
