# Generated by Django 4.1.2 on 2023-04-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_image_created_at_image_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageset",
            name="max_size",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
