# Generated by Django 4.1.2 on 2023-04-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0010_imageset_min_size_alter_imageset_max_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageset",
            name="max_size",
            field=models.IntegerField(default=10),
        ),
    ]
